### ISSUE TITLE
about Unicode path

### ISSUE THREAD

**Issue by xxdoc** [OlimilO1402/Win_Dialogs#3]
if clicked  mnuEditFolderChoose_Click

Private Function Ptr2String(ByVal lpStrPointer As LongPtr) As String
    Dim lLen As Long
    Dim bBuffer() As Byte
    If lpStrPointer = 0 Then Exit Function
  ‘  lLen = lstrlenW(lpStrPointer) * 2& - 1&     ===============if Unicode may be path error D:\打印机插?  
 ‘can change to 
    lLen = lstrlenW(lpStrPointer) * 2&   ‘=====now work ok   D:\打印机插件
    If lLen > 0& Then
        ReDim bBuffer(lLen)
        RtlMoveMemory bBuffer(0), ByVal lpStrPointer, lLen
        CoTaskMemFree lpStrPointer
        Ptr2String = bBuffer
    End If
End Function

**Comment by OlimilO1402** [comment]
fixed, many thanks for the testing and creating the issue ticket
